name: Run Custom

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: GusAction
        uses: ggdl96/ts-github-action-test@1.0.3
        with:
          message: Hi, this is for test!
